// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6kbCnakvA-pPJbaI3NfglkCWQ_F1Y2M',
    appId: '1:215099942721:web:6a6f43a3a62f99526863c0',
    messagingSenderId: '215099942721',
    projectId: 'gjlm-gallery',
    authDomain: 'gjlm-gallery.firebaseapp.com',
    storageBucket: 'gjlm-gallery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPAoAMZbM49BlUcLmVUG33n6uSRLN25hs',
    appId: '1:215099942721:android:c9de74a42110d0606863c0',
    messagingSenderId: '215099942721',
    projectId: 'gjlm-gallery',
    storageBucket: 'gjlm-gallery.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2D4FhE3Qt96bSXIE2xqMdnFonnxrvcwA',
    appId: '1:215099942721:ios:05f989aa42e8811b6863c0',
    messagingSenderId: '215099942721',
    projectId: 'gjlm-gallery',
    storageBucket: 'gjlm-gallery.firebasestorage.app',
    iosBundleId: 'com.example.gjlmGallery',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2D4FhE3Qt96bSXIE2xqMdnFonnxrvcwA',
    appId: '1:215099942721:ios:05f989aa42e8811b6863c0',
    messagingSenderId: '215099942721',
    projectId: 'gjlm-gallery',
    storageBucket: 'gjlm-gallery.firebasestorage.app',
    iosBundleId: 'com.example.gjlmGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE6kbCnakvA-pPJbaI3NfglkCWQ_F1Y2M',
    appId: '1:215099942721:web:bb4b51a09edff1656863c0',
    messagingSenderId: '215099942721',
    projectId: 'gjlm-gallery',
    authDomain: 'gjlm-gallery.firebaseapp.com',
    storageBucket: 'gjlm-gallery.firebasestorage.app',
  );
}
